blank_issues_enabled: false

contact_links:
  - name: Code of Conduct
    url: https://github.com/inkdex/inkdex.github.io?tab=coc-ov-file#readme
    about: Please read the code of conduct before creating any issue or discussion post.
  - name: Support Guidelines
    url: https://github.com/inkdex/inkdex.github.io/blob/master/.github/SUPPORT.md
    about: Please read the support guidelines before creating any issue or discussion post.
  - name: Asking Questions
    url: https://github.com/inkdex/inkdex.github.io/discussions/categories/q-a
    about: Use the Q&A Discussions section if you want to ask questions.
  - name: Search the Issue Tracker
    url: https://github.com/inkdex/inkdex.github.io/issues?q=is%3Aissue
    about: Check to make sure there is not an issue that is related to yours.
  - name: Our Discord Server
    url: https://discord.gg/inkdex
    about: You can contact us through our Discord server as well.
